artifact_uri: file:///c:/Users/vishw/OneDrive/Documents/intellipaat%20mtech/sem2_sub/deployment%20of%20ml%20models/git%20demo/mlops_EmailSpam_Assignment2/mlruns/832986021826464198/732bef799e974132ab67e3685142f908/artifacts
end_time: 1751652149171
entry_point_name: ''
experiment_id: '832986021826464198'
lifecycle_stage: active
run_id: 732bef799e974132ab67e3685142f908
run_name: languid-kite-837
source_name: ''
source_type: 4
source_version: ''
start_time: 1751652143974
status: 3
tags: []
user_id: vishwajeet
