artifact_uri: file:///c:/Users/vishw/OneDrive/Documents/intellipaat%20mtech/sem2_sub/deployment%20of%20ml%20models/git%20demo/mlops_EmailSpam_Assignment2/mlruns/832986021826464198/ec93052e4ca64a97b810160b8f334454/artifacts
end_time: 1751651896704
entry_point_name: ''
experiment_id: '832986021826464198'
lifecycle_stage: active
run_id: ec93052e4ca64a97b810160b8f334454
run_name: wistful-bear-444
source_name: ''
source_type: 4
source_version: ''
start_time: 1751651891630
status: 3
tags: []
user_id: vishwajeet
