artifact_uri: file:///c:/Users/vishw/OneDrive/Documents/intellipaat%20mtech/sem2_sub/deployment%20of%20ml%20models/git%20demo/mlops_EmailSpam_Assignment2/mlruns/832986021826464198/a3f2095bc1f04bb19a154169459815e8/artifacts
end_time: 1751652122811
entry_point_name: ''
experiment_id: '832986021826464198'
lifecycle_stage: active
run_id: a3f2095bc1f04bb19a154169459815e8
run_name: upset-carp-360
source_name: ''
source_type: 4
source_version: ''
start_time: 1751652117505
status: 3
tags: []
user_id: vishwajeet
