artifact_uri: file:///c:/Users/vishw/OneDrive/Documents/intellipaat%20mtech/sem2_sub/deployment%20of%20ml%20models/git%20demo/mlops_EmailSpam_Assignment2/mlruns/832986021826464198/fa5298a35d4f428f97678c8da6529bd7/artifacts
end_time: 1751652143968
entry_point_name: ''
experiment_id: '832986021826464198'
lifecycle_stage: active
run_id: fa5298a35d4f428f97678c8da6529bd7
run_name: casual-mule-427
source_name: ''
source_type: 4
source_version: ''
start_time: 1751652138496
status: 3
tags: []
user_id: vishwajeet
